// src/app/components/layout/layout.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs';
import { EntitiesService } from '../../services/entities.service';
import { LucideAngularModule, Calendar, Clock, BookOpen, Building, Clipboard, Settings, Truck, Users, Code, ChevronDown, LogOut, Loader2, Menu, X } from 'lucide-angular';

interface User {
  id: string;
  email: string;
  full_name: string;
  role: string;
  company_id?: string;
}

interface NavLink {
  name: string;
  path: string;
  icon: string;
  newTab?: boolean;
}

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    LucideAngularModule
  ],
  templateUrl: './layout.component.html',
  styles: [`
    :host {
      display: block;
    }
  `]
})
export class LayoutComponent implements OnInit {
  user: User | null = null;
  isLoading = true;
  isAdminMenuOpen = false;
  isMobileMenuOpen = false;

  readonly Calendar = Calendar;
  readonly Clock = Clock;
  readonly BookOpen = BookOpen;
  readonly Building = Building;
  readonly Clipboard = Clipboard;
  readonly Settings = Settings;
  readonly Truck = Truck;
  readonly Users = Users;
  readonly Code = Code;
  readonly ChevronDown = ChevronDown;
  readonly LogOut = LogOut;
  readonly Loader2 = Loader2;
  readonly Menu = Menu;
  readonly X = X;

  publicLinks: NavLink[] = [
    { name: 'Book Slot', path: '/booking', icon: 'calendar' },
    { name: 'My Schedule', path: '/schedule', icon: 'clock' },
    { name: 'User Guide', path: '/user-guide', icon: 'book', newTab: true }
  ];

  adminLinks: NavLink[] = [
    { name: 'Companies', path: '/companies', icon: 'building' },
    { name: 'Warehouses', path: '/warehouses', icon: 'building' },
    { name: 'Carriers', path: '/carriers', icon: 'clipboard' },
    { name: 'Dock Config', path: '/docks', icon: 'settings' },
    { name: 'Vehicle Types', path: '/vehicle-types', icon: 'truck' },
    { name: 'Users', path: '/users', icon: 'users' },
    { name: 'Booking API', path: '/api', icon: 'code' }
  ];

  constructor(
    private router: Router,
    private entities: EntitiesService
  ) { }

  ngOnInit() {
    this.loadUser();

    this.router.events.pipe(
      filter(event => event instanceof NavigationEnd)
    ).subscribe(() => {
      this.loadUser();
      this.closeMobileMenu();
    });
  }

  async loadUser() {
    this.isLoading = true;
    this.user = {
      id: '1',
      email: 'marc@cario.com.au',
      full_name: 'Marc Enriquez',
      role: 'admin',
      company_id: '1'
    };
    this.isLoading = false;
  }

  async handleLogout() {
    try {
      const userEntity = (this.entities.User as any);
      if (userEntity && typeof userEntity.logout === 'function') {
        await userEntity.logout();
      }
      this.user = null;
      this.router.navigate(['/booking']);
    } catch (e) {
      console.error('Logout failed:', e);
    }
  }

  toggleAdminMenu() {
    this.isAdminMenuOpen = !this.isAdminMenuOpen;
  }

  closeAdminMenu() {
    this.isAdminMenuOpen = false;
  }

  toggleMobileMenu() {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }

  closeMobileMenu() {
    this.isMobileMenuOpen = false;
    this.isAdminMenuOpen = false;
  }

  getFilteredAdminLinks(): NavLink[] {
    if (this.user?.role === 'company_admin') {
      return this.adminLinks.filter(link => link.path === '/users');
    }
    return this.adminLinks;
  }

  getIconComponent(icon: string) {
    const iconMap: Record<string, any> = {
      calendar: this.Calendar,
      clock: this.Clock,
      book: this.BookOpen,
      building: this.Building,
      clipboard: this.Clipboard,
      settings: this.Settings,
      truck: this.Truck,
      users: this.Users,
      code: this.Code
    };
    return iconMap[icon] || this.Calendar;
  }
}

<div class="min-h-screen bg-slate-50">
  <header class="bg-gradient-to-r from-slate-900 to-slate-800 text-white shadow-md">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <a routerLink="/booking" class="flex items-center space-x-2 text-white">
            <i-lucide [img]="Truck" class="w-8 h-8 text-blue-500"></i-lucide>
            <span class="text-xl font-bold">PalletSlot</span>
          </a>
        </div>

        <nav class="hidden md:flex items-center space-x-4">
          <a *ngFor="let link of publicLinks"
             [routerLink]="link.path"
             [target]="link.newTab ? '_blank' : '_self'"
             [rel]="link.newTab ? 'noopener noreferrer' : ''"
             routerLinkActive="bg-blue-600"
             [routerLinkActiveOptions]="{exact: false}"
             class="flex items-center space-x-2 px-3 py-2 rounded-md text-sm font-medium text-slate-200 hover:bg-blue-800 hover:text-white transition-colors">
            <i-lucide [img]="getIconComponent(link.icon)" class="w-4 h-4"></i-lucide>
            <span>{{link.name}}</span>
          </a>

          <div *ngIf="user && (user.role === 'admin' || user.role === 'company_admin')" class="relative">
            <button (click)="toggleAdminMenu()"
                    class="flex items-center space-x-2 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                    [class.bg-blue-600]="isAdminMenuOpen"
                    [class.text-slate-200]="!isAdminMenuOpen"
                    [class.hover:bg-blue-800]="!isAdminMenuOpen">
              <span>Admin</span>
              <i-lucide [img]="ChevronDown" class="w-4 h-4 transition-transform" [class.rotate-180]="isAdminMenuOpen"></i-lucide>
            </button>
            <div *ngIf="isAdminMenuOpen"
                 class="absolute left-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-50"
                 (mouseleave)="closeAdminMenu()">
              <a *ngFor="let item of getFilteredAdminLinks()"
                 [routerLink]="item.path"
                 (click)="closeAdminMenu()"
                 class="flex items-center space-x-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100">
                <i-lucide [img]="getIconComponent(item.icon)" class="w-4 h-4"></i-lucide>
                <span>{{item.name}}</span>
              </a>
            </div>
          </div>
        </nav>

        <div class="flex items-center space-x-4">
          <div *ngIf="isLoading" class="text-slate-400">
            <i-lucide [img]="Loader2" class="w-6 h-6 animate-spin"></i-lucide>
          </div>
          <div *ngIf="!isLoading && user" class="flex items-center space-x-4">
            <span class="hidden sm:inline text-sm text-slate-300">Welcome, {{user.full_name}}</span>
            <button (click)="handleLogout()"
                    class="p-2 text-slate-300 hover:bg-blue-800 hover:text-white rounded-md transition-colors"
                    title="Logout">
              <i-lucide [img]="LogOut" class="w-5 h-5"></i-lucide>
            </button>
          </div>

          <button (click)="toggleMobileMenu()"
                  class="md:hidden p-2 text-white hover:bg-blue-800 rounded-md transition-colors"
                  [attr.aria-label]="isMobileMenuOpen ? 'Close menu' : 'Open menu'">
            <i-lucide [img]="Menu" *ngIf="!isMobileMenuOpen" class="w-6 h-6"></i-lucide>
            <i-lucide [img]="X" *ngIf="isMobileMenuOpen" class="w-6 h-6"></i-lucide>
          </button>
        </div>
      </div>

      <div *ngIf="isMobileMenuOpen"
           class="md:hidden border-t border-slate-700 py-4 space-y-2">
        <a *ngFor="let link of publicLinks"
           [routerLink]="link.path"
           [target]="link.newTab ? '_blank' : '_self'"
           [rel]="link.newTab ? 'noopener noreferrer' : ''"
           (click)="!link.newTab && closeMobileMenu()"
           routerLinkActive="bg-blue-600"
           [routerLinkActiveOptions]="{exact: false}"
           class="flex items-center space-x-2 px-3 py-2 rounded-md text-sm font-medium text-slate-200 hover:bg-blue-800 hover:text-white transition-colors">
          <i-lucide [img]="getIconComponent(link.icon)" class="w-4 h-4"></i-lucide>
          <span>{{link.name}}</span>
        </a>

        <div *ngIf="user && (user.role === 'admin' || user.role === 'company_admin')">
          <button (click)="toggleAdminMenu()"
                  class="w-full flex items-center justify-between px-3 py-2 rounded-md text-sm font-medium text-slate-200 hover:bg-blue-800 hover:text-white transition-colors">
            <span>Admin</span>
            <i-lucide [img]="ChevronDown" class="w-4 h-4 transition-transform" [class.rotate-180]="isAdminMenuOpen"></i-lucide>
          </button>
          <div *ngIf="isAdminMenuOpen" class="ml-4 mt-2 space-y-2">
            <a *ngFor="let item of getFilteredAdminLinks()"
               [routerLink]="item.path"
               (click)="closeMobileMenu()"
               routerLinkActive="bg-blue-600"
               class="flex items-center space-x-2 px-3 py-2 rounded-md text-sm text-slate-300 hover:bg-blue-800 hover:text-white transition-colors">
              <i-lucide [img]="getIconComponent(item.icon)" class="w-4 h-4"></i-lucide>
              <span>{{item.name}}</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </header>

  <main>
    <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <ng-content></ng-content>
    </div>
  </main>
</div>

// src/pages/Layout.jsx


import React, { useState, useEffect } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { User } from "@/api/entities";
import { createPageUrl } from "@/utils";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import {
  Menu,
  Calendar,
  Clock,
  Book,
  LogIn,
  LogOut,
  Loader2,
  Settings,
  Building,
  Users,
  Truck,
  ChevronDown,
  ClipboardList,
  Code, // Added Code icon
} from "lucide-react";

export default function Layout({ children, currentPageName }) {
  const [user, setUser] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isAdminMenuOpen, setIsAdminMenuOpen] = useState(false);
  const location = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    const fetchUser = async () => {
      try {
        const currentUser = await User.me();
        setUser(currentUser);
      } catch (e) {
        setUser(null);
      } finally {
        setIsLoading(false);
      }
    };
    fetchUser();
  }, [location.pathname]);

  // Standalone page logic
  if (currentPageName === 'DriverKiosk') {
    return <>{children}</>;
  }

  const handleLogout = async () => {
    await User.logout();
    setUser(null);
    navigate(createPageUrl("Booking"));
  };

  const publicLinks = [
    { name: "Book Slot", page: "Booking", icon: Calendar },
    { name: "My Schedule", page: "Schedule", icon: Clock },
    { name: "User Guide", page: "UserGuide", icon: Book, newTab: true },
  ];

  const privateLinks = [];

  const adminMenuItems = [
    { name: "Companies", page: "Companies", icon: Building },
    { name: "Warehouses", page: "Warehouses", icon: Building },
    { name: "Carriers", page: "Carriers", icon: ClipboardList },
    { name: "Dock Config", page: "Docks", icon: Settings },
    { name: "Vehicle Types", page: "VehicleTypes", icon: Truck },
    { name: "Users", page: "Users", icon: Users },
    { name: "Booking API", page: "API", icon: Code }, // Added Booking API
  ];

  const NavLink = ({ to, isActive, children, newTab = false }) => (
    <Link
      to={to}
      target={newTab ? "_blank" : "_self"}
      rel={newTab ? "noopener noreferrer" : ""}
      className={`flex items-center space-x-2 px-3 py-2 rounded-md text-sm font-medium transition-colors ${
        isActive && !newTab
          ? "bg-blue-600 text-white"
          : "text-slate-200 hover:bg-blue-800 hover:text-white"
      }`}
      onClick={() => !newTab && setIsMobileMenuOpen(false)}
    >
      {children}
    </Link>
  );

  const AdminMenu = () => {
    // Filter admin menu items based on user role
    const filteredAdminMenuItems = user?.role === 'company_admin'
      ? adminMenuItems.filter(item => item.page === 'Users')
      : adminMenuItems; // Admin sees all

    if (filteredAdminMenuItems.length === 0) {
      return null; // Don't render admin menu if there are no items
    }

    return (
      <div className="relative">
        <button
          onClick={() => setIsAdminMenuOpen(!isAdminMenuOpen)}
          className={`flex items-center space-x-2 px-3 py-2 rounded-md text-sm font-medium transition-colors ${
            isAdminMenuOpen || filteredAdminMenuItems.some(item => item.page === currentPageName)
              ? "bg-blue-600 text-white"
              : "text-slate-200 hover:bg-blue-800 hover:text-white"
          }`}
        >
          <span>Admin</span>
          <ChevronDown className={`w-4 h-4 transition-transform ${isAdminMenuOpen ? 'rotate-180' : ''}`} />
        </button>
        {isAdminMenuOpen && (
          <div 
            className="absolute left-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-50"
            onMouseLeave={() => setIsAdminMenuOpen(false)}
          >
            {filteredAdminMenuItems.map((item) => (
              <Link
                key={item.page}
                to={createPageUrl(item.page)}
                className="flex items-center space-x-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100"
                onClick={() => setIsAdminMenuOpen(false)}
              >
                <item.icon className="w-4 h-4" />
                <span>{item.name}</span>
              </Link>
            ))}
          </div>
        )}
      </div>
    );
  };
  
  const renderNavLinks = (isMobile = false) => (
    <nav className={`flex ${isMobile ? 'flex-col space-y-2' : 'flex-row items-center space-x-4'}`}>
      {[...publicLinks, ...privateLinks].map((link) => (
        <NavLink
          key={link.page}
          to={createPageUrl(link.page)}
          isActive={currentPageName === link.page}
          newTab={link.newTab}
        >
          <link.icon className="w-4 h-4" />
          <span>{link.name}</span>
        </NavLink>
      ))}
      {user && (user.role === 'admin' || user.role === 'company_admin') && <AdminMenu />}
    </nav>
  );

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="bg-gradient-to-r from-slate-900 to-slate-800 text-white shadow-md">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center">
              <Link to={createPageUrl("Booking")} className="flex items-center space-x-2 text-white">
                <Truck className="w-8 h-8 text-blue-500" />
                <span className="text-xl font-bold">PalletSlot</span>
              </Link>
            </div>

            {/* Desktop Navigation */}
            <div className="hidden md:block">
              {renderNavLinks()}
            </div>

            <div className="flex items-center">
              {isLoading ? (
                <Loader2 className="w-6 h-6 animate-spin text-slate-400" />
              ) : user ? (
                <div className="flex items-center space-x-4">
                  <span className="hidden sm:inline text-sm text-slate-300">Welcome, {user.full_name}</span>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={handleLogout}
                    className="text-slate-300 hover:bg-blue-800 hover:text-white"
                  >
                    <LogOut className="w-5 h-5" />
                  </Button>
                </div>
              ) : (
                <Link to={createPageUrl("Login")}>
                  <Button className="bg-blue-600 hover:bg-blue-700">
                    <LogIn className="w-5 h-5 mr-2" />
                    Login
                  </Button>
                </Link>
              )}

              {/* Mobile Menu Button */}
              <div className="md:hidden ml-4">
                <Sheet open={isMobileMenuOpen} onOpenChange={setIsMobileMenuOpen}>
                  <SheetTrigger asChild>
                    <Button variant="ghost" size="icon" className="text-white hover:bg-blue-800">
                      <Menu className="w-6 h-6" />
                    </Button>
                  </SheetTrigger>
                  <SheetContent side="left" className="bg-slate-900 text-white border-r-slate-700">
                    <div className="p-4">
                      <div className="flex items-center space-x-2 text-white mb-8">
                        <Truck className="w-8 h-8 text-blue-500" />
                        <span className="text-xl font-bold">PalletSlot</span>
                      </div>
                      {renderNavLinks(true)}
                    </div>
                  </SheetContent>
                </Sheet>
              </div>
            </div>
          </div>
        </div>
      </header>
      <main>
        <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
          {children}
        </div>
      </main>
    </div>
  );
}
